version: "3"

services:
  web:
    build: .
    image: havrlant
    restart: on-failure
    command: node index.js
    volumes:
      - ./controllers:/app/controllers
      - ./databases:/app/databases
      - ./definitions:/app/definitions
      - ./modules:/app/modules
      - ./plugins:/app/plugins
      - ./public:/app/public
      - ./resources:/app/resources
      - ./tmp:/app/tmp
      - ./views:/app/views
      - ./index.js.json:/app/index.js.json
    ports:
      - "8000:8000"
#    env_file: .env
    labels:
      - "traefik.frontend.rule=Host:www.havrlant.xn--krl-fla.com, havrlant.xn--krl-fla.com"
      - "traefik.docker.network=traefik_default"


networks:
  default:
    external:
      name: traefik_default
